GENERATED_MARKER_SIZE = 400

# CHECKING CELL INSIDES
# this is set, so the whole
CELL_MIN_THRESHOLD_HEIGHT = 2.5
CELL_MIN_THRESHOLD_WIDTH = 2.5
THRESHOLD_MINIMAL_POINTS = 5
CELL_THRESHOLD_BINARY = 200

# ARUCO FIND
ARUCO_BLUR_KERNEL_SIZE = (1, 1)
ARUCO_BLUR_SIGMAX = 0

WARPED_IMAGE_WIDTH = 800
WARPED_IMAGE_HEIGHT = 800

# TABLE LAYOUT
TABLE_COLS = 10
TABLE_FIRST_COL_WIDTH = 158
TABLE_LAST_COL_WIDTH = 78
TABLE_ROWS = 20
TABLE_SKIPPED_ROWS = [0, 2, 3]

# CONTOUR RECOGNITION
CONTOUR_BLUR_KERNEL_SIZE = (5, 5)
CONTOUR_BLUR_SIGMAX = 0
CONTOUR_CANNY_THRESHOLD1 = 50
CONTOUR_CANNY_THRESHOLD2 = 150

# COLORS
COLOR_RED = (0, 0, 255)
COLOR_GREEN = (0, 255, 0)
COLOR_BLUE = (255, 0, 0)
